name = "nfp"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Nfp"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
experimental.module = true
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.unusedVariables = true
weak.linter.unreachableTactic = true
weak.linter.missingDocs = true
weak.linter.unusedTactic = true
weak.linter.omit = true
weak.linter.style.longFile = 1500
weak.linter.style.setOption = true
weak.linter.style.missingEnd = true
weak.linter.style.openClassical = true
weak.linter.style.show = true
weak.linter.style.lambdaSyntax = true
weak.linter.style.dollarSyntax = true
weak.linter.style.cdot = true
weak.linter.style.longLine = true
weak.linter.nfp.noHeartbeats = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "stable"

[[lean_lib]]
name = "Nfp"
roots = ["Nfp"]

[[lean_exe]]
name = "nfp"
root = "Main"

[[lean_exe]]
name = "theorem-axioms"
root = "TheoremAxioms"
